### Load data

In [4]:
import numpy as np

def parse_line(line):
    return [int(x) for x in list(line.strip())]

with open('input.txt') as f:
    data = np.array([parse_line(line) for line in f])

print(data)

[[0 1 0 ... 0 1 0]
 [0 1 1 ... 1 0 0]
 [1 1 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 0]
 [0 1 1 ... 1 0 0]
 [0 1 0 ... 1 0 1]]


### Part 1

In [44]:
def convert_to_base10(bitvector):
    return int(''.join(bitvector.astype(str)), base=2)

most_common = data.sum(axis=0) >= len(data) / 2
most_common = most_common.astype(int)
gamma_rate = convert_to_base10(most_common)
epsilon_rate = convert_to_base10(np.abs(most_common - 1))

gamma_rate * epsilon_rate

3895776

### Part 2

In [78]:
def filter_numbers(nums, bit=0, least_common=False):
    if len(nums) == 1:
        return nums.flatten()
    if least_common:
        common = np.sum(nums[:,bit]) < len(nums) / 2
    else:
        common = np.sum(nums[:,bit]) >= len(nums) / 2
    return filter_numbers(nums[nums[:,bit] == common], bit+1, least_common)

oxygen_gen_rating = convert_to_base10(filter_numbers(data))
CO2_scrubber_rating = convert_to_base10(filter_numbers(data, least_common=True))

oxygen_gen_rating * CO2_scrubber_rating

7928162